name: Precise Auto PR

on:
  push:
    branches:
      - 'release/*'

jobs:
  auto-pr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: set git config
      run: |
        git config --global user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"
        git config --global user.name "${GITHUB_ACTOR}"
        git config -l

    - name: check branch names
      id: branch_info
      run: |
        git fetch
        RELEASE_VERSIONS=$(git branch -r | grep 'release/' | cut -d '/' -f 3 | sort -V)
        CURRENT_VERSION=$(echo $GITHUB_REF | rev | cut -d '/' -f 1 | rev)
        ME_AND_MY_NEXT=$(echo "$RELEASE_VERSIONS" | grep -w $CURRENT_VERSION -A 1)
        NUM=$(echo "$ME_AND_MY_NEXT" | wc -l)
        if (( NUM > 1 )); then
          NEXT_VERSION=$(echo "$ME_AND_MY_NEXT" | tail -n 1)
          NEXT_BRANCH="release/$NEXT_VERSION"
          set -x
        else
          echo "No more higher release versions, will merge to main"
          NEXT_VERSION="main"
          NEXT_BRANCH="main"
          set -x
        fi
        echo "NEXT_VERSION=$NEXT_VERSION" >> $GITHUB_OUTPUT
        echo "NEXT_BRANCH=$NEXT_BRANCH" >> $GITHUB_OUTPUT
        echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_OUTPUT
        echo "CURRENT_BRANCH=$CURRENT_BRANCH" >> $GITHUB_OUTPUT

    - name: create pr branch
      id: create_branch
      run: |
        git fetch
        PRBRANCH=auto-pr-${{github.event.after}}-${{steps.branch_info.outputs.NEXT_VERSION}}
        git switch -C ${PRBRANCH} ${{steps.branch_info.outputs.CURRENT_BRANCH}}
        echo "PRBRANCH=$PRBRANCH" >> $GITHUB_OUTPUT

    - name: Pick up commits
      run: |
        echo "PICKRESULT<<EOF" >> $GITHUB_OUTPUT
        for commit in $(git rev-list ${{github.event.commits[0].id}}..${{github.event.after}}); do
          $(git cherry-pick -X theirs $commit) >> $GITHUB_OUTPUT
        done
        echo "EOF" >> $GITHUB_OUTPUT
        git push --set-upstream origin ${{steps.create_branch.outputs.PRBRANCH}}

    - name: Create Pull Request
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh pr create \
              --base ${{steps.branch_info.outputs.NEXT_BRANCH}} \
              --head ${{steps.create_branch.outputs.PRBRANCH}} \
              --title "Auto PR from release/${{steps.branch_info.outputs.CURRENT_VERSION}}" \
              --body "Create by AutoPR\n ${{steps.create_branch.outputs.PICKRESULT}}}"